### ISSUE TITLE
Upload does not start at all (on 404)

### ISSUE THREAD

**Issue by Myrmex** [DmitryEfimenko/FlowJs-MVC#1]
Hi, I found this sample code when looking to a solution for my issue at http://stackoverflow.com/questions/29694470/uploading-files-with-flow-js-ng-flow-to-webapi-2 . Yet, it seems that your code too is affected by the same issue: as soon as flow.js gets a 404 from the API, it stops and no upload takes place.

According to the docs at flowjs, "you should allow for the same chunk to be uploaded more than once; this isn't standard behaviour, but on an unstable network environment it could happen, and this case is exactly what Flow.js is designed for. For every request, you can confirm reception in HTTP status codes [...]: 200: The chunk was accepted and correct. No need to re-upload. 404, 415. 500, 501: The file for which the chunk was uploaded is not supported, cancel the entire upload. Anything else: Something went wrong, but try reuploading the file.".

Thus, it would appear that returning 404 inhibits the upload altogether. In my code sample (see my stackoverflow post) I tried returning Accepted instead of Not Found; yet nothing changes, and the upload does not happen. 

Could anyone help in setting up an up-to-date, simple, working code example for using flow.js with WebAPI 2? Interested readers can find a full repro solution in the post quoted above.

**Comment by AidasK** [comment]
https://github.com/DmitryEfimenko/FlowJs-MVC/blob/master/Controllers/FileController.cs#L36
204 status should be returned, because 404 is considered a fatal error.

**Comment by DmitryEfimenko** [comment]
404 is considered a fatal error during the chunk upload - not during the [test chunk request](https://github.com/flowjs/flow.js/blob/master/README.md#handling-get-or-test-requests):

> If request returns anything else, the chunk will be uploaded in the standard fashion.

For me it works just fine. I get 404 during the test chunk request and flowjs moves on with the uploading of that chunk. It does not stop.

**Comment by Myrmex** [comment]
Thank you, at least for the current flow.js release I got a reply to my SO post: unless you change the flow.js configuration, you must return 204, rather than 404, which stops the upload.
