### ISSUE TITLE
IFileManagerService interface not found

### ISSUE THREAD

**Issue by manirafiq** [DmitryEfimenko/FlowJs-MVC#2]
in FileController.cs class IFileManagerService interface not found exception occurred for me. 
and
i want to save other types of files including image files.
Kindly help me.

**Comment by DmitryEfimenko** [comment]
in my controller `IFileManagerService` is an example service that you'd have. It's basically a service that will know what to do with a file once it's available. You have to create and implement it yourself.
This plugin allows you to manage the file types that you want to allow to be uploaded through validation:

```
validationRules.AcceptedExtensions.AddRange(new List<string> { "jpeg", "jpg", "png", "bmp" });
```

Just update it however you need.

**Comment by manirafiq** [comment]
Can you please give me a sample code of <code>IFileManagerService </code> service to save file.

**Comment by DmitryEfimenko** [comment]
You do not even need it. Just delete anything that has to do with `IFileManagerService`. The file should be uploaded into the temp folder
