### ISSUE TITLE
Validation Rules: File extension check is case sensistive

### ISSUE THREAD

**Issue by jokecamp** [DmitryEfimenko/FlowJs-MVC#3]
First off, great work with this library. Not really a big issue but wanted to put this here in case others have the same confusion.

It took me a while to realize why it was not accepting my WAV when I had listed wav file types.

Thanks!

**Comment by DmitryEfimenko** [comment]
so what was the issue?

**Comment by jokecamp** [comment]
This bit here should be replaced with a case insensitive comparison. 

`rules.AcceptedExtensions.SingleOrDefault(x => x == FileName.Split('.').Last()) == null)`

**Comment by DmitryEfimenko** [comment]
good catch! I'll update code
