### ISSUE TITLE
Migration to Net Core

### ISSUE THREAD

**Issue by ruisilva450** [DmitryEfimenko/FlowJs-MVC#6]
Hey,

I know this repo is stale but wanted to know if there is something out there that represents the same as this repo for .Net Core

Thanks

**Comment by DmitryEfimenko** [comment]
I"m not aware of such, sorry

**Comment by ruisilva450** [comment]
It's ok, I migrated the code from [@samhowes](https://github.com/samhowes)'s [NgFlowSample](https://github.com/samhowes/NgFlowSample) to .Net Core. 

I added it [here](https://github.com/ruisilva450/FlowJs-NetCore). 

Also will add to the [Backend on ASP.NET MVC](https://github.com/flowjs/flow.js/blob/master/samples/Backend%20on%20ASP.NET%20MVC.md) list
